services:
  grafana:
    image: grafana/grafana:latest
    container_name: pkb-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_PROTOCOL=http
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    networks:
      - monitoring

volumes:
  grafana-storage:
    driver: local

networks:
  monitoring:
    driver: bridge

