apiVersion: v1
kind: Service
metadata:
  name: create-item-service
  labels:
    app: create-item
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: create-item

