apiVersion: v1
kind: Service
metadata:
  name: get-items-service
  labels:
    app: get-items
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: get-items

